//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТипыГрузов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТипыГрузов()
        {
            this.Учёт = new HashSet<Учёт>();
        }
    
        public int ID_груза { get; set; }
        public string Тип_груза { get; set; }
        public string Условия_перевозки { get; set; }
        public string Класс_опасности { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учёт> Учёт { get; set; }
    }
}
