//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Транспорт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Транспорт()
        {
            this.Учёт = new HashSet<Учёт>();
        }
    
        public int ID_Транспорта { get; set; }
        public string Марка { get; set; }
        public string Модель { get; set; }
        public Nullable<int> Год_выпуска { get; set; }
        public Nullable<int> Грузоподъемность_тонн { get; set; }
        public string ГосНомер { get; set; }
        public Nullable<int> Тип { get; set; }
    
        public virtual Типы_траспорта Типы_траспорта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учёт> Учёт { get; set; }
    }
}
