//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учёт
    {
        public int ID_Наряда { get; set; }
        public Nullable<int> Водитель { get; set; }
        public Nullable<int> Тип_груза { get; set; }
        public Nullable<int> Транспорт { get; set; }
        public Nullable<int> Маршрут { get; set; }
        public Nullable<System.TimeSpan> Время_простоя { get; set; }
        public Nullable<System.DateTime> Дата_отгрузки { get; set; }
        public Nullable<System.DateTime> Дата_прибытия { get; set; }
        public Nullable<int> Статус { get; set; }
        public Nullable<int> Оператор { get; set; }
        public Nullable<int> Масса_груза_тонн { get; set; }
    
        public virtual Водители Водители { get; set; }
        public virtual Маршруты Маршруты { get; set; }
        public virtual Операторы Операторы { get; set; }
        public virtual Статус Статус1 { get; set; }
        public virtual ТипыГрузов ТипыГрузов { get; set; }
        public virtual Транспорт Транспорт1 { get; set; }
    }
}
